In [67]:
import numpy as np 
import matplotlib.pyplot as plt 

In [68]:
mockup_data = np.array([
    [16000,32000, 500],
    [36000, 36000, 500]
])

mockup_data_2 = mockup_data.copy()
mockup_data_2[:,1] += 6500
mockup_data, mockup_data_2

(array([[16000, 32000,   500],
        [36000, 36000,   500]]),
 array([[16000, 38500,   500],
        [36000, 42500,   500]]))

In [69]:
HORIZONTAL_MAX = 228000
VERTICAL_MAX = 228000

In [70]:
mockup_data[:][0][1] % HORIZONTAL_MAX  * (2 * np.pi / HORIZONTAL_MAX)

np.float64(0.8818505694287138)

In [71]:
def sensor_2_spher(h,v,l):
    h_c = h % HORIZONTAL_MAX * (2*np.pi /HORIZONTAL_MAX)
    v_c = v % VERTICAL_MAX *(2*np.pi / VERTICAL_MAX)

    return h_c, v_c, l

In [72]:
spher1 = []
spher2 = []

for meas in mockup_data:
    spher1.append(sensor_2_spher(meas[0], meas[1], meas[2]))
for meas in mockup_data_2:
    spher2.append(sensor_2_spher(meas[0], meas[1], meas[2]))

spher1, spher2 = np.array(spher1), np.array(spher2)

spher1, spher2

(array([[4.40925285e-01, 8.81850569e-01, 5.00000000e+02],
        [9.92081891e-01, 9.92081891e-01, 5.00000000e+02]]),
 array([[4.40925285e-01, 1.06097647e+00, 5.00000000e+02],
        [9.92081891e-01, 1.17120779e+00, 5.00000000e+02]]))

In [73]:
spher1[0]-spher1[1], spher2[0]- spher2[1]

(array([-0.55115661, -0.11023132,  0.        ]),
 array([-0.55115661, -0.11023132,  0.        ]))

In [74]:
def spher_2_xyz(h_angle,v_angle,r):
    x = r * np.sin(v_angle) * np.cos(h_angle)
    y = r * np.sin(v_angle) * np.sin(h_angle)
    z = r * np.cos(v_angle)

    return x,y,z

In [75]:
xyz1 = []
xyz2 = []

for coord in spher1:
    xyz1.append(spher_2_xyz(coord[0], coord[1], coord[2]))
for coord in spher2:
    xyz2.append(spher_2_xyz(coord[0], coord[1], coord[2]))

xyz1, xyz2 = np.array(xyz1), np.array(xyz2)

xyz1, xyz2

(array([[349.04417536, 164.71791839, 317.8618741 ],
        [228.94333166, 350.42385616, 273.47407906]]),
 array([[394.67613067, 186.25215738, 244.01001158],
        [251.93010462, 385.60773141, 194.51966446]]))

In [76]:
xyz1[0] - xyz1[1], xyz2[0]-xyz2[1]

(array([ 120.1008437 , -185.70593777,   44.38779504]),
 array([ 142.74602605, -199.35557403,   49.49034712]))

In [ ]:
import scipy as sp 
sp.